version=1.0.0
group=com.ludwici.carpetscore

minecraft_version=1.20.1

mod_name=Carpets Core
mod_author=ludwici
mod_id=carpetscore
license=MIT
description=Simple lib for creating multifaced carpets.
minecraft_version_range=[1.20.1,1.20.4)

fabric_version=0.92.2+1.20.1
fabric_loader_version=0.15.11

forge_version=47.3.1
forge_loader_version_range=[47,)
forge_version_range=[47,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
